//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.EntityClient;

namespace AccountsAtAGlance.Model
{
    public partial class AccountsAtAGlanceContainer : ObjectContext
    {
        public const string ConnectionString = "name=AccountsAtAGlanceContainer";
        public const string ContainerName = "AccountsAtAGlanceContainer";
    
        #region Constructors
    
        public AccountsAtAGlanceContainer()
            : base(ConnectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public AccountsAtAGlanceContainer(string connectionString)
            : base(connectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public AccountsAtAGlanceContainer(EntityConnection connection)
            : base(connection, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        #endregion
    
        #region ObjectSet Properties
    
        public ObjectSet<Order> Orders
        {
            get { return _orders  ?? (_orders = CreateObjectSet<Order>("Orders")); }
        }
        private ObjectSet<Order> _orders;
    
        public ObjectSet<Security> Securities
        {
            get { return _securities  ?? (_securities = CreateObjectSet<Security>("Securities")); }
        }
        private ObjectSet<Security> _securities;
    
        public ObjectSet<WatchList> WatchLists
        {
            get { return _watchLists  ?? (_watchLists = CreateObjectSet<WatchList>("WatchLists")); }
        }
        private ObjectSet<WatchList> _watchLists;
    
        public ObjectSet<OrderType> OrderTypes
        {
            get { return _orderTypes  ?? (_orderTypes = CreateObjectSet<OrderType>("OrderTypes")); }
        }
        private ObjectSet<OrderType> _orderTypes;
    
        public ObjectSet<Exchange> Exchanges
        {
            get { return _exchanges  ?? (_exchanges = CreateObjectSet<Exchange>("Exchanges")); }
        }
        private ObjectSet<Exchange> _exchanges;
    
        public ObjectSet<BrokerageAccount> BrokerageAccounts
        {
            get { return _brokerageAccounts  ?? (_brokerageAccounts = CreateObjectSet<BrokerageAccount>("BrokerageAccounts")); }
        }
        private ObjectSet<BrokerageAccount> _brokerageAccounts;
    
        public ObjectSet<MarketIndex> MarketIndexes
        {
            get { return _marketIndexes  ?? (_marketIndexes = CreateObjectSet<MarketIndex>("MarketIndexes")); }
        }
        private ObjectSet<MarketIndex> _marketIndexes;
    
        public ObjectSet<Position> Positions
        {
            get { return _positions  ?? (_positions = CreateObjectSet<Position>("Positions")); }
        }
        private ObjectSet<Position> _positions;
    
        public ObjectSet<Customer> Customers
        {
            get { return _customers  ?? (_customers = CreateObjectSet<Customer>("Customers")); }
        }
        private ObjectSet<Customer> _customers;

        #endregion
        #region Function Imports
        public ObjectResult<Nullable<int>> DeleteAccounts()
        {
            return base.ExecuteFunction<Nullable<int>>("DeleteAccounts");
        }
        public ObjectResult<Nullable<int>> DeleteSecuritiesAndExchanges()
        {
            return base.ExecuteFunction<Nullable<int>>("DeleteSecuritiesAndExchanges");
        }

        #endregion
    }
}
